dataset_config:
  in1_masked_coco:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    features:
      train:
      - /nas/home/ziyidou/mmf_data/datasets/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
      val:
      - /nas/home/ziyidou/mmf_data/datasets/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
      test:
      - /nas/home/ziyidou/mmf_data/datasets/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
    annotations:
      train:
      - coco/defaults/annotations/imdb_karpathy_train_by_image.npy
      val:
      - coco/defaults/annotations/imdb_karpathy_val_by_image.npy
      test:
      - coco/defaults/annotations/imdb_karpathy_test_by_image.npy
    max_features: 100
    two_sentence: false
    two_sentence_probability: 0.5
    false_caption: false
    false_caption_probability: 0.5
    use_image_feature_masks: false
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 128
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.90
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: boxes
          image_width_key: image_w
          image_height_key: image_h
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
